### ISSUE TITLE
Date display problem

### ISSUE THREAD

**Issue by lizenghui** [jellyfin/jellyfin-plugin-reports#55] opened 2022-01-26 01:14 UTC
system:ubuntu20.04
The timezone of my OS is: Asia/Shanghai
System time is normal
But the time displayed by the reports plugin is wrong, it doesn't take into account my time zone, it is the first 8 hours of my time, please tell me what to do?

**Comment by AlfredJKwack** [comment] 2022-05-03 18:14
Duplicate of #35

**Closed** 2022-05-05 13:03 UTC
